fix: implement correct clone for JewishCalendar
The getUpcomingParsha function called clone, which created a new JewishDate object instead of a JewishCalendar object. The former lacks the necessary getParsha function causing an error when called:

TypeError: clone.getParsha is not a function. (In 'clone.getParsha()', 'clone.getParsha' is undefined)